### ISSUE TITLE
add "bright", to balance "dim"?

### ISSUE THREAD

**Issue by Pomax** [chalk/chalk#113]
Given that the `dim` style (`\x1b[2m`) is available, it would make sense to also offer the `bright` style (`\x1b[1m`).

**Comment by Qix-** [comment]
You want `.bold()`. :)

**Comment by Pomax** [comment]
Okay, let's reopen this to make that name make sense, because I do *not* want bold, I want the upper 8 bright colors in the 16 color palette. Let's at the very least add `bright()` as an alias for `bold()` if that's really what it does.

**Comment by Qix-** [comment]
@pomax Windows is the only system that treats the Bold render mode as 'bright'. Many emulators simply bolden the number and rely on the `9x` and `10x` render modes to do the brighter colors. Unfortunately the same escape is used for both bold and bright intermittently on different emulators and documentation has been pretty consistently showing that it's a *bold* escape rather than a bright one.

Another explanation for why Windows does it is because the renderer for the windows command prompt doesn't support multiple fonts, so it can't really do true *bold* text and thus mimics it via the brighter palette. I've seen a number of terminal emulators that treat bold as just *bold*, with no color changes.

As well, if you use `\x1b[1;38;5;241m` (bold, and then a 256-palette color) most emulators still show the same color as if it wasn't bold, with just a thicker typeface.

Bold is the correct name here, and wasn't a decision really made by the chalk team. Bright is specific for (in my opinion, incorrectly implemented) terminal emulators on non-UNIX-ey systems, e.g. Windows.
