### ISSUE TITLE
Dumping objects outputs [object Object]

### ISSUE THREAD

**Issue by HillTravis** [chalk/chalk#118]
If you pass an object instead of a string, what gets dumped is `[object Object]` instead of the actual dump of that object. One solution could be to possibly check if it's of type 'object' and if so, either just return the object unstyled, or `JSON.stringify()` it, but I'm not sure that's ideal.

**Comment by sindresorhus** [comment]
Not interested in changing that behavior. It's been like that for years and you're the first to complain. If I had done it again I would have typechecked the input and thrown a TypeError, but that's not worth doing a breaking change over.

**Comment by Qix-** [comment]
@HillTravis for the record, you could always do

```javascript
console.log(require('util').inspect(obj, {colors:true, depth:null}));
```

**Comment by HillTravis** [comment]
@Qix- thanks, I didn't know about that!

**Comment by JanisE** [comment]
@Qix- , thanks for the polite reply! :)

Yes, I'm lazy. That's why I'm searching for a library, not using `'\x1b[36m%s\x1b[0m'`-like prefixes for outputting messages.

My use-case is that I do not want any fancy colouring options, like boldness, different colours of the same message and the like – which Chalk offers.

I just want the `console.log` output to be coloured depending on the log level (debug, info, warn, error), that's it.

For me, it seems simple enough for me to hope for an existing Node module that does this. Apparently, I just came across this library that turned out to be meant for something else.

**Comment by Qix-** [comment]
@JanisE write a helper script:

```javascript
// log.js
const chalk = require('chalk');

module.exports = {
    info: (...args) => console.log(chalk.cyan(...args)),
    warning: (...args) => console.log(chalk.yellow(...args)),
    error: (...args) => console.log(chalk.red(...args))
};
```

```javascript
const log = require('./log');

log.info('This is an info in Cyan');
log.warning('This is a warning in Yellow');
log.error('This is an error in Red');
```

Then you can customize the output format how you like in the log.js file.

**Comment by JanisE** [comment]
Thank you! :)

**Comment by dwasyluk** [comment]
> @HillTravis for the record, you could always do
> 
> ```js
> console.log(require('util').inspect(obj, {colors:true, depth:null}));
> ```

This saved me, thank you!

**Comment by johan44co** [comment]
console.log(chalk.blue(require('util').inspect(obj, {colors:true, depth:null})));

**Comment by Qix-** [comment]
Most other libraries use `util.inspect` or `JSON.stringify`. This is explicitly a non-goal of Chalk.

Locking as there's nothing left to do here. Thank you everyone for your input.
