### ISSUE TITLE
Chrome DevTools Support

### ISSUE THREAD

**Issue by jacob-israel-turner** [chalk/chalk#152]
First, thanks for this library!  It's very useful!

Recently, [Chrome DevTools has added support for debugging Node processes](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27).  This makes it possible to log to both the process in the terminal, and the Chrome DevTools.

Unfortunately, while using your library, this makes logging in Chrome unsightly.  The Chrome console does not handle the color formatting in the same way that the terminal does.  For example:

In the terminal:
![In the terminal](https://cloud.githubusercontent.com/assets/8698364/26210707/ba5e1eec-3bad-11e7-8b34-b5e2fc31c7a5.png)

Same output, but in the Chrome DevTools:
![In Chrome DevTools](https://cloud.githubusercontent.com/assets/8698364/26210708/ba64cb20-3bad-11e7-8513-114d8850d4d0.png)

Apparently you [can format Chrome logs](http://stackoverflow.com/a/13017382).

I'm wondering if there is anything we can do to make this experience any better.  Is there a way we can print in a format that works in both Chrome and the terminal?  If not, can we opt in to DevTools formatting (which would presumably, and acceptably, make the terminal less readable)?

**Comment by Qix-** [comment]
This library isn't for chrome. It's for the terminal. That's completely out of scope for this project.

If you really wanted it, check out packages like `xterm.js` to use in conjunction.

**Comment by lostpebble** [comment]
While I can see why this might be considered out of the scope of the project (a sole focus on terminal and the colour interface for that), more people are now using Chrome Devtools as their terminal for Node.js projects because of its usefulness. Chalk seems to be a historically popular choice for some server logging libraries, and this causes messed up logs in the console. `koa-logger` being the culprit in my case. A compatibility mode (perhaps just a global off switch) would be great if possible, but understandable if not desired for this project.

**Comment by Qix-** [comment]
```
require('chalk').enabled = false;
```

**Comment by lostpebble** [comment]
So simple and does the job. Thanks!
