### ISSUE TITLE
Replace colors.js with chalk

### ISSUE THREAD

**Issue by xxczaki** [chalk/chalk#227]
Hi!
My package is using colors.js, but i'm trying to replace it with chalk. I've got a problem with this:

loading.succeed(`${chalk.green(money.convert(amount, { from: from, to: item }).toFixed(2))} ${`(${item})`.gray} ${currencies[item].italic}`)

and this:

console.log(chalk.underline.gray(` Conversion of ${from.bold} ${amount.bold}`))

I was trying to change some things, but that doesn't work. What should i do to use only chalk?

Full code: https://github.com/xxczaki/cash-cli/blob/master/bin/cash.js

**Comment by sindresorhus** [comment]
Support questions are better asked on Stack Overflow. The issue tracker is for actual issues.

But to answer you question, instead of using the properties on the objects, wrap them in a chalk call. So `${from.bold}` becomes `${chalk.bold(from)}`.

Or you can use the [tagged template literal](https://github.com/chalk/chalk#tagged-template-literal):

```js
chalk`Conversion of {bold ${from}} {bold ${amount}}`
```
