### ISSUE TITLE
Is a typescript rewrite a possibility ?

### ISSUE THREAD

**Issue by MonsieurMan** [chalk/chalk#239]
> Hello, I just saw that the library I was using for quite a long time was really small and for all the time it saved me I thought I could contribute back to it.   

The thing is that I'm quite a typescript fellow and would like to rewrite it if you consider it would be a good thing.

Here are a few arguments:
- Automatic up to date typescript definitions
- Trivial flow definitions
- Cleaner object oriented paradigm if necessary
- No change for users *(in the api if we want, but it would require a major version bump)*
- Remove module exporting logic from business logic
- Easy, fast and secure *(rewriting)* with the 100% coverage it actually has

**Comment by thetutlage** [comment]
> Disclaimer: I am not the author and neither the contributor to chalk. But since I use it heavily, here is my say

I am not against Typescript, but I do see every popular project has atleast one issue talking about Type definition support or a re-write in Typescript.

So I personally think, Typescript has done much harm than good, since each author has to say no to the request or spend their precious time in supporting something that is literally 0% value in output.

**Comment by sindresorhus** [comment]
I appreciate the offer, but I don't want to have a compile-step for this module or go through the churn of rewriting it now that we already have a type definition. Chalk is pretty much done at this point, so there won't be many TS definition changes anyway.

If you're looking to contribute with TypeScript, I could use some help with https://github.com/sindresorhus/is/issues/35 and also see if there are any improvements we could do to do TS codebase ;)
