### ISSUE TITLE
TypeScript: Property Accessors Throwing Error

### ISSUE THREAD

**Issue by shellscape** [chalk/chalk#283]
I'm attempting to dynamically access color functions off of the default export like so:

```js
import chalk from 'chalk';

const colorName: string = 'red';
const color = chalk[colorName];
```

And I'm getting back the following from the compiler on the `chalk[colorName]` line:

```console
Element implicitly has an 'any' type because type 'Chalk & { supportsColor: ColorSupport; }' has no index signature.
```

I believe the typings for `chalk` are slightly amiss?

**Comment by 43081j** [comment]
This is just because `colorName` could be anything.

Try typing it as `keyof` instead:

```ts
import chalk, { Chalk } from 'chalk';

const colorName: keyof Chalk = 'red';
const color = chalk[colorName];
```

If you don't know what `colorName` will be in reality (so it could be an invalid color name), you should have a function which checks its a valid key and types it as `keyof Chalk`.

Like `isValid(k: string): k is keyof Chalk`.

**Comment by shellscape** [comment]
Thanks for that tip. I'll give it a try and report back.

**Comment by ulivz** [comment]
When I tried

```ts
import chalk, { Chalk } from 'chalk'

function(color: keyof Chalk, ...args: any[]) {
    console.log(chalk[color](label), ...args)
}
```'

I got following error:

```
TS7017: Element implicitly has an 'any' type because type 'Chalk & { supportsColor: ColorSupport; }' has no index signature.
```
