### ISSUE TITLE
Performance testing as CI step?

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk#302]
Since we're wanting to be more performance-oriented going into v3, is there something we could add to the CI step to test for performance regressions?

**Comment by sindresorhus** [comment]
@GeorgeGkas Sounds good, but there needs to be some kind of threshold, so it doesn't fail if it's like `0.001` performance regression. We also need a way to ignore certain metrics in case a performance regression is unavoidable due to fixing a bug. Would have really preferred a benchmark CI of some sort or a comprehensive tool, but I know of nothing like this, so I guess a custom script will have to do.

**Comment by GeorgeGkas** [comment]
@sindresorhus should I proceed with the implementation?

**Comment by sindresorhus** [comment]
Yes, go ahead :)

**Comment by GeorgeGkas** [comment]
What should be the threshold value? I run the benchmark suit multiple times to get a clearer picture. The max dispersion of some tests tends to be up to 5.000 op/s. This happens because I use a script to handle the whole test process with the actual test suit to run from a child process. I tried other options but couldn't get better results. The final question is how to handle the case when one test gives results of `x` op/s and when we re-run it again we get `x-2000` op/s?

**Comment by sindresorhus** [comment]
I'm going to close this as nothing has happened here for years and it's not essential. I think the best solution is for someone to make a reusable GitHub Actions workflow for this.
