### ISSUE TITLE
Invalid type definition for `supports-color` reexport 

### ISSUE THREAD

**Issue by langpavel** [chalk/chalk#318]

**Comment by Qix-** [comment]
Can you add some context to this? I have no idea what this is about.

**Comment by tomstoneham** [comment]
Unless I'm mistaken, based on @langpavel's commit referencing this issue (b1322ea), I believe this has now been fixed in #347? I think the issue was just that the supports-color module's `stdout` export (which is re-exported by chalk as `supportsColor`) may be false in the case that there is no colour support at all, but the type definitions didn't reflect this.

**Comment by Qix-** [comment]
Thanks @tomstoneham, closing unless @langpavel wants to add more context if the issue hasn't been fixed.

**Comment by langpavel** [comment]
Hmm, I'm lost track of this. Reopen if appropriate.
