### ISSUE TITLE
Using chalk with winston to log both on the Terminal and on a .txt file.

### ISSUE THREAD

**Issue by xXnikosXx** [chalk/chalk#423]
Im using winstonjs to log both to the Terminal and to a txt file. When logging to the terminal using chalk, everything is as expected, properly color, no issues there. Is there any way I can get my colors to show on the txt file (or some other file format) as well?

**Comment by Qix-** [comment]
Nope, unfortunately not. The escape sequences we use are specifically for a terminal - they don't work with e.g. RTF files.

The reason why we shut them off when piping to another process or to a file is because those codes tend to break the other programs since they're only meant for displaying in a terminal.

You'll want to find a package that creates RTF files and the like.
