### ISSUE TITLE
spacing issue using prompt-sync and chalk

### ISSUE THREAD

**Issue by obscuredc** [chalk/chalk#517]
Hello! I have a small project I was working on. I was rewriting it, starting from scratch, because I had written my own, slower functions for color-coding. So this time, I decided to use chalk. However, when I used my code, some weird spacing issue occurred in between where the cursor should be and where it was. A screenshot, and the code, are attached below.

Here's the code I was using:
```js
const chalk = require("chalk");
const prompt = require("prompt-sync")();
console.log(prompt(chalk.green("$ ")));
```
![Screenshot (1478)_LI](https://user-images.githubusercontent.com/77344064/137588928-e0692423-2197-490a-ac2c-11ebbf51880a.jpg)
If it isn't visible in the image, the cursor is almost always 10 spaces in front of where it should be (at the typed text)

**Comment by obscuredc** [comment]
Another note: there is no space when not using the chalk coloring.

**Comment by Qix-** [comment]
Because prompt-sync is doing `.length` on the input string, which will also report all of the escape codes needed to display colored text. However, what's actually printed to the screen has less characters.

This is a bug in prompt-sync, I suppose - either they shouldn't be taking into account the length of the input, or they should strip escape codes prior to taking the length, if they want to support color codes at all. You'd have to open an issue with them, though.

There's one hack you might be able to try, though no guarantees:

```javascript
const wrapPrompt = text => ({
    length: text.length,
    toString: () => chalk.green(text)
});

promptSync(wrapPrompt("$ "));
```

Though even if it works I don't _really_ recommend doing that for anything other than toy scripts. If you do, I suggest hard-pinning the version of `prompt-sync` in your package.json (i.e. remove any range characters like `^` or `~`) just to avoid any surprises.

Hope that helps! Closing this since there's nothing actionable from our end.
