### ISSUE TITLE
cjs compliant alternatives

### ISSUE THREAD

**Issue by suprMax** [chalk/chalk#543]
Hi there,

Did anyone already fork this repo with CJS support? I'm sitting on several old codebases that I would like to keep secure/up to date but not spend too much time on maintenance. Is there a drop in replacement?

**Comment by sindresorhus** [comment]
Nothing official, but: https://npms.io/search?q=chalk+commonjs

If you're in an async context, you could use `await import('chalk')` which is how you can import ESM in CommonJS.

**Comment by suprMax** [comment]
node doesn't support await on root script level

**Comment by suprMax** [comment]
To answer my own question for others having the same issue:

https://github.com/lukeed/kleur
https://github.com/jorgebucaran/colorette

Both excellent drop in replacements. I went with `kleur`.

Thanks for great library @[sindresorhus](https://github.com/sindresorhus). It's unfortunate that people can't use chalk/got/regexp to string anymore.

**Comment by Qix-** [comment]
Users are definitely able to use the libraries just fine. We just choose not to support unsupported platforms in new major versions.

**Comment by suprMax** [comment]
CommonJS is fully supported in Node LTS and Current. It’s neither legacy nor deprecated and ESM makes zero to no sense in node land. You’re breaking people’s code for no good reason. 

But it’s always the risk with OSS, so as I said, thanks for creating and maintaining until now and best of luck in the future.

**Comment by suprMax** [comment]
CommonJS is still stable in Current version of NodeJS. It’s not deprecated or legacy.

**Comment by Qix-** [comment]
CommonJS is [effectively frozen](https://github.com/nodejs/node/issues/33954#issuecomment-789992629). It is unsupported in the sense that there is no development being done anymore. Most bundlers and tools that are frequently used these days do not support CommonJS. There are a number of drawbacks with CommonJS that made it difficult to work with at times. Putting it nicely, CommonJS is dying. Node.js committee won't deprecate it because they can't. That doesn't mean you should use it (the prominent example being `url.parse()` - it will never be removed, but you should not use it in new code).

It is _absolutely_ considered legacy, though, by many people, including many on the Node.js teams themselves. ESM is now a language level construct. It is not an opinion, it is objectively _the_ way to structure modern Javascript code. It makes the most sense to use it over one of the other arbitrary frameworks that allowed module loading (there were many - Node just happened to choose CJS).

Most projects these days use ESM. Most packages that are still maintained have migrated to ESM. Most tooling, bundlers, and analyzers rely on ESM. Ergonomically speaking, ESM is easier to reason about when you care about reasoning about javascript as a whole. These are maintainership decisions we chose for Chalk given that Chalk is one of the top 10 most depended upon packages.

---

You are definitely welcome to pin to v4, which is still CJS. I'm sure any vulnerabilities we find will be backported to a degree for a little while (no guarantees). There are no known vulnerabilities for chalk v4 that I'm personally aware of. Given the breadth of usage and the relative simplicity of the package, I would imagine that remaining the case at this point.

But please do not come here and assert that people can no longer use the package because the latest version doesn't work in _your own personal_ legacy codebase. That is not our problem, and only insults maintainers who put their own free time and effort into giving _you_ free code to use, for _free_, with relatively loose requirements on your part. I've lost almost all tolerance for such comments.

Best of luck.
