### ISSUE TITLE
Color not represented inside macOS terminal

### ISSUE THREAD

**Issue by jpstijn** [chalk/chalk#563]
When building my own CLI Tool i sometimes find the color not correctly displayed: 

When printing the following:

```
const yellow = chalk.hex("#FFD833");

console.log(yellow(`(v${version})\n`));
```
Expected: 
![image](https://user-images.githubusercontent.com/24881734/189590951-700cbcfe-ed98-4b42-9810-87ac3efefce3.png)

Received:
<img width="68" alt="Screenshot 2022-09-12 at 08 51 54" src="https://user-images.githubusercontent.com/24881734/189590822-eccb4cd1-c557-463f-808c-b2e85e02d6d7.png">

Does anyone know what is going wrong? (I know i have not provided much detail)

**Comment by Qix-** [comment]
The MacOS terminal doesn't support Truecolor. You need to use an [Ansi256](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) color with `.ansi256(code)` instead, or install `color-convert` and do `const yellow = chalk.ansi256(colorConvert.hex.ansi256('#FFD833'))` (this used to be built-in functionality but we removed it due to it being bulky and atypical usage).

Hope that helps!

**Comment by jpstijn** [comment]
Sorry my mistake! Thanks for your reply.
